
title: "Wietze"
subtitle: Cyber troublemaker ｜ Threat Hunting, Detection Engineering &amp; Research ｜ <a href="https://www.twitter.com/wietze">@Wietze</a>
post_tags: [cyber, threat detection, cyber threat, cyber threat detection, edr, endpoint, blue team, blue teaming, red team, red teaming, threat hunting, threat hunter, hunting]
sass:
    style: compressed
    sass_dir: _sass
footer: yes
footer_text: "← Go back"
footer_url: "/"
permalink: /blog/:title
favicon_location: "/img/favicon.png"
