
title: "Wietze"
subtitle: Cyber troublemaker ｜ Threat Detection and Response ｜ <a href="https://www.twitter.com/wietze">@Wietze</a>
sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_text: "← Go back"
footer_url: "/"
permalink: /blog/:title
favicon: Yes
favicon_location: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAFVBMVEUAAAAAAAC4iz/Jxcb/wVf/7EX///9nHf7dAAAAAXRSTlMAQObYZgAAAFJJREFUeAFVzVEKBDEMguEYYu5/5LVS1unPEOr3MlWFUyXsksR3j2oEtB6gRr+AguD2hz2RgaEL9LjALQClayDWv4WvYPT52ReUnwUdu0IlqOwfCCAB4pZooF8AAAAASUVORK5CYII="
